<?php

namespace App\Helpers;

class KabupatenKota
{
  /**
   * Daftar seluruh Kabupaten/Kota di Indonesia
   */
  public static function all(): array
  {
    return [
      // === ACEH ===
      'Kab. Aceh Barat' => 'Kab. Aceh Barat',
      'Kab. Aceh Barat Daya' => 'Kab. Aceh Barat Daya',
      'Kab. Aceh Besar' => 'Kab. Aceh Besar',
      'Kab. Aceh Jaya' => 'Kab. Aceh Jaya',
      'Kab. Aceh Selatan' => 'Kab. Aceh Selatan',
      'Kab. Aceh Singkil' => 'Kab. Aceh Singkil',
      'Kab. Aceh Tamiang' => 'Kab. Aceh Tamiang',
      'Kab. Aceh Tengah' => 'Kab. Aceh Tengah',
      'Kab. Aceh Tenggara' => 'Kab. Aceh Tenggara',
      'Kab. Aceh Timur' => 'Kab. Aceh Timur',
      'Kab. Aceh Utara' => 'Kab. Aceh Utara',
      'Kab. Bener Meriah' => 'Kab. Bener Meriah',
      'Kab. Bireuen' => 'Kab. Bireuen',
      'Kab. Gayo Lues' => 'Kab. Gayo Lues',
      'Kab. Nagan Raya' => 'Kab. Nagan Raya',
      'Kab. Pidie' => 'Kab. Pidie',
      'Kab. Pidie Jaya' => 'Kab. Pidie Jaya',
      'Kab. Simeulue' => 'Kab. Simeulue',
      'Kota Banda Aceh' => 'Kota Banda Aceh',
      'Kota Langsa' => 'Kota Langsa',
      'Kota Lhokseumawe' => 'Kota Lhokseumawe',
      'Kota Sabang' => 'Kota Sabang',
      'Kota Subulussalam' => 'Kota Subulussalam',

      // === SUMATERA UTARA ===
      'Kab. Asahan' => 'Kab. Asahan',
      'Kab. Batu Bara' => 'Kab. Batu Bara',
      'Kab. Dairi' => 'Kab. Dairi',
      'Kab. Deli Serdang' => 'Kab. Deli Serdang',
      'Kab. Humbang Hasundutan' => 'Kab. Humbang Hasundutan',
      'Kab. Karo' => 'Kab. Karo',
      'Kab. Labuhanbatu' => 'Kab. Labuhanbatu',
      'Kab. Labuhanbatu Selatan' => 'Kab. Labuhanbatu Selatan',
      'Kab. Labuhanbatu Utara' => 'Kab. Labuhanbatu Utara',
      'Kab. Langkat' => 'Kab. Langkat',
      'Kab. Mandailing Natal' => 'Kab. Mandailing Natal',
      'Kab. Nias' => 'Kab. Nias',
      'Kab. Nias Barat' => 'Kab. Nias Barat',
      'Kab. Nias Selatan' => 'Kab. Nias Selatan',
      'Kab. Nias Utara' => 'Kab. Nias Utara',
      'Kab. Padang Lawas' => 'Kab. Padang Lawas',
      'Kab. Padang Lawas Utara' => 'Kab. Padang Lawas Utara',
      'Kab. Pakpak Bharat' => 'Kab. Pakpak Bharat',
      'Kab. Samosir' => 'Kab. Samosir',
      'Kab. Serdang Bedagai' => 'Kab. Serdang Bedagai',
      'Kab. Simalungun' => 'Kab. Simalungun',
      'Kab. Tapanuli Selatan' => 'Kab. Tapanuli Selatan',
      'Kab. Tapanuli Tengah' => 'Kab. Tapanuli Tengah',
      'Kab. Tapanuli Utara' => 'Kab. Tapanuli Utara',
      'Kab. Toba' => 'Kab. Toba',
      'Kota Binjai' => 'Kota Binjai',
      'Kota Gunungsitoli' => 'Kota Gunungsitoli',
      'Kota Medan' => 'Kota Medan',
      'Kota Padangsidimpuan' => 'Kota Padangsidimpuan',
      'Kota Pematang Siantar' => 'Kota Pematang Siantar',
      'Kota Sibolga' => 'Kota Sibolga',
      'Kota Tanjungbalai' => 'Kota Tanjungbalai',
      'Kota Tebing Tinggi' => 'Kota Tebing Tinggi',

      // === SUMATERA BARAT ===
      'Kab. Agam' => 'Kab. Agam',
      'Kab. Dharmasraya' => 'Kab. Dharmasraya',
      'Kab. Kepulauan Mentawai' => 'Kab. Kepulauan Mentawai',
      'Kab. Lima Puluh Kota' => 'Kab. Lima Puluh Kota',
      'Kab. Padang Pariaman' => 'Kab. Padang Pariaman',
      'Kab. Pasaman' => 'Kab. Pasaman',
      'Kab. Pasaman Barat' => 'Kab. Pasaman Barat',
      'Kab. Pesisir Selatan' => 'Kab. Pesisir Selatan',
      'Kab. Sijunjung' => 'Kab. Sijunjung',
      'Kab. Solok' => 'Kab. Solok',
      'Kab. Solok Selatan' => 'Kab. Solok Selatan',
      'Kab. Tanah Datar' => 'Kab. Tanah Datar',
      'Kota Bukittinggi' => 'Kota Bukittinggi',
      'Kota Padang' => 'Kota Padang',
      'Kota Padang Panjang' => 'Kota Padang Panjang',
      'Kota Pariaman' => 'Kota Pariaman',
      'Kota Payakumbuh' => 'Kota Payakumbuh',
      'Kota Sawahlunto' => 'Kota Sawahlunto',
      'Kota Solok' => 'Kota Solok',

      // === RIAU ===
      'Kab. Bengkalis' => 'Kab. Bengkalis',
      'Kab. Indragiri Hilir' => 'Kab. Indragiri Hilir',
      'Kab. Indragiri Hulu' => 'Kab. Indragiri Hulu',
      'Kab. Kampar' => 'Kab. Kampar',
      'Kab. Kepulauan Meranti' => 'Kab. Kepulauan Meranti',
      'Kab. Kuantan Singingi' => 'Kab. Kuantan Singingi',
      'Kab. Pelalawan' => 'Kab. Pelalawan',
      'Kab. Rokan Hilir' => 'Kab. Rokan Hilir',
      'Kab. Rokan Hulu' => 'Kab. Rokan Hulu',
      'Kab. Siak' => 'Kab. Siak',
      'Kota Dumai' => 'Kota Dumai',
      'Kota Pekanbaru' => 'Kota Pekanbaru',

      // === JAMBI ===
      'Kab. Batanghari' => 'Kab. Batanghari',
      'Kab. Bungo' => 'Kab. Bungo',
      'Kab. Kerinci' => 'Kab. Kerinci',
      'Kab. Merangin' => 'Kab. Merangin',
      'Kab. Muaro Jambi' => 'Kab. Muaro Jambi',
      'Kab. Sarolangun' => 'Kab. Sarolangun',
      'Kab. Tanjung Jabung Barat' => 'Kab. Tanjung Jabung Barat',
      'Kab. Tanjung Jabung Timur' => 'Kab. Tanjung Jabung Timur',
      'Kab. Tebo' => 'Kab. Tebo',
      'Kota Jambi' => 'Kota Jambi',
      'Kota Sungai Penuh' => 'Kota Sungai Penuh',

      // === SUMATERA SELATAN ===
      'Kab. Banyuasin' => 'Kab. Banyuasin',
      'Kab. Empat Lawang' => 'Kab. Empat Lawang',
      'Kab. Lahat' => 'Kab. Lahat',
      'Kab. Muara Enim' => 'Kab. Muara Enim',
      'Kab. Musi Banyuasin' => 'Kab. Musi Banyuasin',
      'Kab. Musi Rawas' => 'Kab. Musi Rawas',
      'Kab. Musi Rawas Utara' => 'Kab. Musi Rawas Utara',
      'Kab. Ogan Ilir' => 'Kab. Ogan Ilir',
      'Kab. Ogan Komering Ilir' => 'Kab. Ogan Komering Ilir',
      'Kab. Ogan Komering Ulu' => 'Kab. Ogan Komering Ulu',
      'Kab. Ogan Komering Ulu Selatan' => 'Kab. Ogan Komering Ulu Selatan',
      'Kab. Ogan Komering Ulu Timur' => 'Kab. Ogan Komering Ulu Timur',
      'Kab. Penukal Abab Lematang Ilir' => 'Kab. Penukal Abab Lematang Ilir',
      'Kota Lubuklinggau' => 'Kota Lubuklinggau',
      'Kota Pagar Alam' => 'Kota Pagar Alam',
      'Kota Palembang' => 'Kota Palembang',
      'Kota Prabumulih' => 'Kota Prabumulih',

      // === BENGKULU ===
      'Kab. Bengkulu Selatan' => 'Kab. Bengkulu Selatan',
      'Kab. Bengkulu Tengah' => 'Kab. Bengkulu Tengah',
      'Kab. Bengkulu Utara' => 'Kab. Bengkulu Utara',
      'Kab. Kaur' => 'Kab. Kaur',
      'Kab. Kepahiang' => 'Kab. Kepahiang',
      'Kab. Lebong' => 'Kab. Lebong',
      'Kab. Mukomuko' => 'Kab. Mukomuko',
      'Kab. Rejang Lebong' => 'Kab. Rejang Lebong',
      'Kab. Seluma' => 'Kab. Seluma',
      'Kota Bengkulu' => 'Kota Bengkulu',

      // === LAMPUNG ===
      'Kab. Lampung Barat' => 'Kab. Lampung Barat',
      'Kab. Lampung Selatan' => 'Kab. Lampung Selatan',
      'Kab. Lampung Tengah' => 'Kab. Lampung Tengah',
      'Kab. Lampung Timur' => 'Kab. Lampung Timur',
      'Kab. Lampung Utara' => 'Kab. Lampung Utara',
      'Kab. Mesuji' => 'Kab. Mesuji',
      'Kab. Pesawaran' => 'Kab. Pesawaran',
      'Kab. Pesisir Barat' => 'Kab. Pesisir Barat',
      'Kab. Pringsewu' => 'Kab. Pringsewu',
      'Kab. Tanggamus' => 'Kab. Tanggamus',
      'Kab. Tulang Bawang' => 'Kab. Tulang Bawang',
      'Kab. Tulang Bawang Barat' => 'Kab. Tulang Bawang Barat',
      'Kab. Way Kanan' => 'Kab. Way Kanan',
      'Kota Bandar Lampung' => 'Kota Bandar Lampung',
      'Kota Metro' => 'Kota Metro',

      // === KEPULAUAN BANGKA BELITUNG ===
      'Kab. Bangka' => 'Kab. Bangka',
      'Kab. Bangka Barat' => 'Kab. Bangka Barat',
      'Kab. Bangka Selatan' => 'Kab. Bangka Selatan',
      'Kab. Bangka Tengah' => 'Kab. Bangka Tengah',
      'Kab. Belitung' => 'Kab. Belitung',
      'Kab. Belitung Timur' => 'Kab. Belitung Timur',
      'Kota Pangkalpinang' => 'Kota Pangkalpinang',

      // === KEPULAUAN RIAU ===
      'Kab. Bintan' => 'Kab. Bintan',
      'Kab. Karimun' => 'Kab. Karimun',
      'Kab. Kepulauan Anambas' => 'Kab. Kepulauan Anambas',
      'Kab. Lingga' => 'Kab. Lingga',
      'Kab. Natuna' => 'Kab. Natuna',
      'Kota Batam' => 'Kota Batam',
      'Kota Tanjungpinang' => 'Kota Tanjungpinang',

      // === DKI JAKARTA ===
      'Kab. Kepulauan Seribu' => 'Kab. Kepulauan Seribu',
      'Kota Jakarta Barat' => 'Kota Jakarta Barat',
      'Kota Jakarta Pusat' => 'Kota Jakarta Pusat',
      'Kota Jakarta Selatan' => 'Kota Jakarta Selatan',
      'Kota Jakarta Timur' => 'Kota Jakarta Timur',
      'Kota Jakarta Utara' => 'Kota Jakarta Utara',

      // === JAWA BARAT ===
      'Kab. Bandung' => 'Kab. Bandung',
      'Kab. Bandung Barat' => 'Kab. Bandung Barat',
      'Kab. Bekasi' => 'Kab. Bekasi',
      'Kab. Bogor' => 'Kab. Bogor',
      'Kab. Ciamis' => 'Kab. Ciamis',
      'Kab. Cianjur' => 'Kab. Cianjur',
      'Kab. Cirebon' => 'Kab. Cirebon',
      'Kab. Garut' => 'Kab. Garut',
      'Kab. Indramayu' => 'Kab. Indramayu',
      'Kab. Karawang' => 'Kab. Karawang',
      'Kab. Kuningan' => 'Kab. Kuningan',
      'Kab. Majalengka' => 'Kab. Majalengka',
      'Kab. Pangandaran' => 'Kab. Pangandaran',
      'Kab. Purwakarta' => 'Kab. Purwakarta',
      'Kab. Subang' => 'Kab. Subang',
      'Kab. Sukabumi' => 'Kab. Sukabumi',
      'Kab. Sumedang' => 'Kab. Sumedang',
      'Kab. Tasikmalaya' => 'Kab. Tasikmalaya',
      'Kota Bandung' => 'Kota Bandung',
      'Kota Banjar' => 'Kota Banjar',
      'Kota Bekasi' => 'Kota Bekasi',
      'Kota Bogor' => 'Kota Bogor',
      'Kota Cimahi' => 'Kota Cimahi',
      'Kota Cirebon' => 'Kota Cirebon',
      'Kota Depok' => 'Kota Depok',
      'Kota Sukabumi' => 'Kota Sukabumi',
      'Kota Tasikmalaya' => 'Kota Tasikmalaya',

      // === JAWA TENGAH ===
      'Kab. Banjarnegara' => 'Kab. Banjarnegara',
      'Kab. Banyumas' => 'Kab. Banyumas',
      'Kab. Batang' => 'Kab. Batang',
      'Kab. Blora' => 'Kab. Blora',
      'Kab. Boyolali' => 'Kab. Boyolali',
      'Kab. Brebes' => 'Kab. Brebes',
      'Kab. Cilacap' => 'Kab. Cilacap',
      'Kab. Demak' => 'Kab. Demak',
      'Kab. Grobogan' => 'Kab. Grobogan',
      'Kab. Jepara' => 'Kab. Jepara',
      'Kab. Karanganyar' => 'Kab. Karanganyar',
      'Kab. Kebumen' => 'Kab. Kebumen',
      'Kab. Kendal' => 'Kab. Kendal',
      'Kab. Klaten' => 'Kab. Klaten',
      'Kab. Kudus' => 'Kab. Kudus',
      'Kab. Magelang' => 'Kab. Magelang',
      'Kab. Pati' => 'Kab. Pati',
      'Kab. Pekalongan' => 'Kab. Pekalongan',
      'Kab. Pemalang' => 'Kab. Pemalang',
      'Kab. Purbalingga' => 'Kab. Purbalingga',
      'Kab. Purworejo' => 'Kab. Purworejo',
      'Kab. Rembang' => 'Kab. Rembang',
      'Kab. Semarang' => 'Kab. Semarang',
      'Kab. Sragen' => 'Kab. Sragen',
      'Kab. Sukoharjo' => 'Kab. Sukoharjo',
      'Kab. Tegal' => 'Kab. Tegal',
      'Kab. Temanggung' => 'Kab. Temanggung',
      'Kab. Wonogiri' => 'Kab. Wonogiri',
      'Kab. Wonosobo' => 'Kab. Wonosobo',
      'Kota Magelang' => 'Kota Magelang',
      'Kota Pekalongan' => 'Kota Pekalongan',
      'Kota Salatiga' => 'Kota Salatiga',
      'Kota Semarang' => 'Kota Semarang',
      'Kota Surakarta' => 'Kota Surakarta',
      'Kota Tegal' => 'Kota Tegal',

      // === DI YOGYAKARTA ===
      'Kab. Bantul' => 'Kab. Bantul',
      'Kab. Gunungkidul' => 'Kab. Gunungkidul',
      'Kab. Kulon Progo' => 'Kab. Kulon Progo',
      'Kab. Sleman' => 'Kab. Sleman',
      'Kota Yogyakarta' => 'Kota Yogyakarta',

      // === JAWA TIMUR ===
      'Kab. Bangkalan' => 'Kab. Bangkalan',
      'Kab. Banyuwangi' => 'Kab. Banyuwangi',
      'Kab. Blitar' => 'Kab. Blitar',
      'Kab. Bojonegoro' => 'Kab. Bojonegoro',
      'Kab. Bondowoso' => 'Kab. Bondowoso',
      'Kab. Gresik' => 'Kab. Gresik',
      'Kab. Jember' => 'Kab. Jember',
      'Kab. Jombang' => 'Kab. Jombang',
      'Kab. Kediri' => 'Kab. Kediri',
      'Kab. Lamongan' => 'Kab. Lamongan',
      'Kab. Lumajang' => 'Kab. Lumajang',
      'Kab. Madiun' => 'Kab. Madiun',
      'Kab. Magetan' => 'Kab. Magetan',
      'Kab. Malang' => 'Kab. Malang',
      'Kab. Mojokerto' => 'Kab. Mojokerto',
      'Kab. Nganjuk' => 'Kab. Nganjuk',
      'Kab. Ngawi' => 'Kab. Ngawi',
      'Kab. Pacitan' => 'Kab. Pacitan',
      'Kab. Pamekasan' => 'Kab. Pamekasan',
      'Kab. Pasuruan' => 'Kab. Pasuruan',
      'Kab. Ponorogo' => 'Kab. Ponorogo',
      'Kab. Probolinggo' => 'Kab. Probolinggo',
      'Kab. Sampang' => 'Kab. Sampang',
      'Kab. Sidoarjo' => 'Kab. Sidoarjo',
      'Kab. Situbondo' => 'Kab. Situbondo',
      'Kab. Sumenep' => 'Kab. Sumenep',
      'Kab. Trenggalek' => 'Kab. Trenggalek',
      'Kab. Tuban' => 'Kab. Tuban',
      'Kab. Tulungagung' => 'Kab. Tulungagung',
      'Kota Batu' => 'Kota Batu',
      'Kota Blitar' => 'Kota Blitar',
      'Kota Kediri' => 'Kota Kediri',
      'Kota Madiun' => 'Kota Madiun',
      'Kota Malang' => 'Kota Malang',
      'Kota Mojokerto' => 'Kota Mojokerto',
      'Kota Pasuruan' => 'Kota Pasuruan',
      'Kota Probolinggo' => 'Kota Probolinggo',
      'Kota Surabaya' => 'Kota Surabaya',

      // === BANTEN ===
      'Kab. Lebak' => 'Kab. Lebak',
      'Kab. Pandeglang' => 'Kab. Pandeglang',
      'Kab. Serang' => 'Kab. Serang',
      'Kab. Tangerang' => 'Kab. Tangerang',
      'Kota Cilegon' => 'Kota Cilegon',
      'Kota Serang' => 'Kota Serang',
      'Kota Tangerang' => 'Kota Tangerang',
      'Kota Tangerang Selatan' => 'Kota Tangerang Selatan',

      // === BALI ===
      'Kab. Badung' => 'Kab. Badung',
      'Kab. Bangli' => 'Kab. Bangli',
      'Kab. Buleleng' => 'Kab. Buleleng',
      'Kab. Gianyar' => 'Kab. Gianyar',
      'Kab. Jembrana' => 'Kab. Jembrana',
      'Kab. Karangasem' => 'Kab. Karangasem',
      'Kab. Klungkung' => 'Kab. Klungkung',
      'Kab. Tabanan' => 'Kab. Tabanan',
      'Kota Denpasar' => 'Kota Denpasar',

      // === NUSA TENGGARA BARAT ===
      'Kab. Bima' => 'Kab. Bima',
      'Kab. Dompu' => 'Kab. Dompu',
      'Kab. Lombok Barat' => 'Kab. Lombok Barat',
      'Kab. Lombok Tengah' => 'Kab. Lombok Tengah',
      'Kab. Lombok Timur' => 'Kab. Lombok Timur',
      'Kab. Lombok Utara' => 'Kab. Lombok Utara',
      'Kab. Sumbawa' => 'Kab. Sumbawa',
      'Kab. Sumbawa Barat' => 'Kab. Sumbawa Barat',
      'Kota Bima' => 'Kota Bima',
      'Kota Mataram' => 'Kota Mataram',

      // === NUSA TENGGARA TIMUR ===
      'Kab. Alor' => 'Kab. Alor',
      'Kab. Belu' => 'Kab. Belu',
      'Kab. Ende' => 'Kab. Ende',
      'Kab. Flores Timur' => 'Kab. Flores Timur',
      'Kab. Kupang' => 'Kab. Kupang',
      'Kab. Lembata' => 'Kab. Lembata',
      'Kab. Malaka' => 'Kab. Malaka',
      'Kab. Manggarai' => 'Kab. Manggarai',
      'Kab. Manggarai Barat' => 'Kab. Manggarai Barat',
      'Kab. Manggarai Timur' => 'Kab. Manggarai Timur',
      'Kab. Nagekeo' => 'Kab. Nagekeo',
      'Kab. Ngada' => 'Kab. Ngada',
      'Kab. Rote Ndao' => 'Kab. Rote Ndao',
      'Kab. Sabu Raijua' => 'Kab. Sabu Raijua',
      'Kab. Sikka' => 'Kab. Sikka',
      'Kab. Sumba Barat' => 'Kab. Sumba Barat',
      'Kab. Sumba Barat Daya' => 'Kab. Sumba Barat Daya',
      'Kab. Sumba Tengah' => 'Kab. Sumba Tengah',
      'Kab. Sumba Timur' => 'Kab. Sumba Timur',
      'Kab. Timor Tengah Selatan' => 'Kab. Timor Tengah Selatan',
      'Kab. Timor Tengah Utara' => 'Kab. Timor Tengah Utara',
      'Kota Kupang' => 'Kota Kupang',

      // === KALIMANTAN BARAT ===
      'Kab. Bengkayang' => 'Kab. Bengkayang',
      'Kab. Kapuas Hulu' => 'Kab. Kapuas Hulu',
      'Kab. Kayong Utara' => 'Kab. Kayong Utara',
      'Kab. Ketapang' => 'Kab. Ketapang',
      'Kab. Kubu Raya' => 'Kab. Kubu Raya',
      'Kab. Landak' => 'Kab. Landak',
      'Kab. Melawi' => 'Kab. Melawi',
      'Kab. Mempawah' => 'Kab. Mempawah',
      'Kab. Sambas' => 'Kab. Sambas',
      'Kab. Sanggau' => 'Kab. Sanggau',
      'Kab. Sekadau' => 'Kab. Sekadau',
      'Kab. Sintang' => 'Kab. Sintang',
      'Kota Pontianak' => 'Kota Pontianak',
      'Kota Singkawang' => 'Kota Singkawang',

      // === KALIMANTAN TENGAH ===
      'Kab. Barito Selatan' => 'Kab. Barito Selatan',
      'Kab. Barito Timur' => 'Kab. Barito Timur',
      'Kab. Barito Utara' => 'Kab. Barito Utara',
      'Kab. Gunung Mas' => 'Kab. Gunung Mas',
      'Kab. Kapuas' => 'Kab. Kapuas',
      'Kab. Katingan' => 'Kab. Katingan',
      'Kab. Kotawaringin Barat' => 'Kab. Kotawaringin Barat',
      'Kab. Kotawaringin Timur' => 'Kab. Kotawaringin Timur',
      'Kab. Lamandau' => 'Kab. Lamandau',
      'Kab. Murung Raya' => 'Kab. Murung Raya',
      'Kab. Pulang Pisau' => 'Kab. Pulang Pisau',
      'Kab. Seruyan' => 'Kab. Seruyan',
      'Kab. Sukamara' => 'Kab. Sukamara',
      'Kota Palangka Raya' => 'Kota Palangka Raya',

      // === KALIMANTAN SELATAN ===
      'Kab. Balangan' => 'Kab. Balangan',
      'Kab. Banjar' => 'Kab. Banjar',
      'Kab. Barito Kuala' => 'Kab. Barito Kuala',
      'Kab. Hulu Sungai Selatan' => 'Kab. Hulu Sungai Selatan',
      'Kab. Hulu Sungai Tengah' => 'Kab. Hulu Sungai Tengah',
      'Kab. Hulu Sungai Utara' => 'Kab. Hulu Sungai Utara',
      'Kab. Kotabaru' => 'Kab. Kotabaru',
      'Kab. Tabalong' => 'Kab. Tabalong',
      'Kab. Tanah Bumbu' => 'Kab. Tanah Bumbu',
      'Kab. Tanah Laut' => 'Kab. Tanah Laut',
      'Kab. Tapin' => 'Kab. Tapin',
      'Kota Banjarbaru' => 'Kota Banjarbaru',
      'Kota Banjarmasin' => 'Kota Banjarmasin',

      // === KALIMANTAN TIMUR ===
      'Kab. Berau' => 'Kab. Berau',
      'Kab. Kutai Barat' => 'Kab. Kutai Barat',
      'Kab. Kutai Kartanegara' => 'Kab. Kutai Kartanegara',
      'Kab. Kutai Timur' => 'Kab. Kutai Timur',
      'Kab. Mahakam Ulu' => 'Kab. Mahakam Ulu',
      'Kab. Paser' => 'Kab. Paser',
      'Kab. Penajam Paser Utara' => 'Kab. Penajam Paser Utara',
      'Kota Balikpapan' => 'Kota Balikpapan',
      'Kota Bontang' => 'Kota Bontang',
      'Kota Samarinda' => 'Kota Samarinda',

      // === KALIMANTAN UTARA ===
      'Kab. Bulungan' => 'Kab. Bulungan',
      'Kab. Malinau' => 'Kab. Malinau',
      'Kab. Nunukan' => 'Kab. Nunukan',
      'Kab. Tana Tidung' => 'Kab. Tana Tidung',
      'Kota Tarakan' => 'Kota Tarakan',

      // === SULAWESI UTARA ===
      'Kab. Bolaang Mongondow' => 'Kab. Bolaang Mongondow',
      'Kab. Bolaang Mongondow Selatan' => 'Kab. Bolaang Mongondow Selatan',
      'Kab. Bolaang Mongondow Timur' => 'Kab. Bolaang Mongondow Timur',
      'Kab. Bolaang Mongondow Utara' => 'Kab. Bolaang Mongondow Utara',
      'Kab. Kepulauan Sangihe' => 'Kab. Kepulauan Sangihe',
      'Kab. Kepulauan Siau Tagulandang Biaro' => 'Kab. Kepulauan Siau Tagulandang Biaro',
      'Kab. Kepulauan Talaud' => 'Kab. Kepulauan Talaud',
      'Kab. Minahasa' => 'Kab. Minahasa',
      'Kab. Minahasa Selatan' => 'Kab. Minahasa Selatan',
      'Kab. Minahasa Tenggara' => 'Kab. Minahasa Tenggara',
      'Kab. Minahasa Utara' => 'Kab. Minahasa Utara',
      'Kota Bitung' => 'Kota Bitung',
      'Kota Kotamobagu' => 'Kota Kotamobagu',
      'Kota Manado' => 'Kota Manado',
      'Kota Tomohon' => 'Kota Tomohon',

      // === SULAWESI TENGAH ===
      'Kab. Banggai' => 'Kab. Banggai',
      'Kab. Banggai Kepulauan' => 'Kab. Banggai Kepulauan',
      'Kab. Banggai Laut' => 'Kab. Banggai Laut',
      'Kab. Buol' => 'Kab. Buol',
      'Kab. Donggala' => 'Kab. Donggala',
      'Kab. Morowali' => 'Kab. Morowali',
      'Kab. Morowali Utara' => 'Kab. Morowali Utara',
      'Kab. Parigi Moutong' => 'Kab. Parigi Moutong',
      'Kab. Poso' => 'Kab. Poso',
      'Kab. Sigi' => 'Kab. Sigi',
      'Kab. Tojo Una-Una' => 'Kab. Tojo Una-Una',
      'Kab. Toli-Toli' => 'Kab. Toli-Toli',
      'Kota Palu' => 'Kota Palu',

      // === SULAWESI SELATAN ===
      'Kab. Bantaeng' => 'Kab. Bantaeng',
      'Kab. Barru' => 'Kab. Barru',
      'Kab. Bone' => 'Kab. Bone',
      'Kab. Bulukumba' => 'Kab. Bulukumba',
      'Kab. Enrekang' => 'Kab. Enrekang',
      'Kab. Gowa' => 'Kab. Gowa',
      'Kab. Jeneponto' => 'Kab. Jeneponto',
      'Kab. Kepulauan Selayar' => 'Kab. Kepulauan Selayar',
      'Kab. Luwu' => 'Kab. Luwu',
      'Kab. Luwu Timur' => 'Kab. Luwu Timur',
      'Kab. Luwu Utara' => 'Kab. Luwu Utara',
      'Kab. Maros' => 'Kab. Maros',
      'Kab. Pangkajene dan Kepulauan' => 'Kab. Pangkajene dan Kepulauan',
      'Kab. Pinrang' => 'Kab. Pinrang',
      'Kab. Sidenreng Rappang' => 'Kab. Sidenreng Rappang',
      'Kab. Sinjai' => 'Kab. Sinjai',
      'Kab. Soppeng' => 'Kab. Soppeng',
      'Kab. Takalar' => 'Kab. Takalar',
      'Kab. Tana Toraja' => 'Kab. Tana Toraja',
      'Kab. Toraja Utara' => 'Kab. Toraja Utara',
      'Kab. Wajo' => 'Kab. Wajo',
      'Kota Makassar' => 'Kota Makassar',
      'Kota Palopo' => 'Kota Palopo',
      'Kota Parepare' => 'Kota Parepare',

      // === SULAWESI TENGGARA ===
      'Kab. Bombana' => 'Kab. Bombana',
      'Kab. Buton' => 'Kab. Buton',
      'Kab. Buton Selatan' => 'Kab. Buton Selatan',
      'Kab. Buton Tengah' => 'Kab. Buton Tengah',
      'Kab. Buton Utara' => 'Kab. Buton Utara',
      'Kab. Kolaka' => 'Kab. Kolaka',
      'Kab. Kolaka Timur' => 'Kab. Kolaka Timur',
      'Kab. Kolaka Utara' => 'Kab. Kolaka Utara',
      'Kab. Konawe' => 'Kab. Konawe',
      'Kab. Konawe Kepulauan' => 'Kab. Konawe Kepulauan',
      'Kab. Konawe Selatan' => 'Kab. Konawe Selatan',
      'Kab. Konawe Utara' => 'Kab. Konawe Utara',
      'Kab. Muna' => 'Kab. Muna',
      'Kab. Muna Barat' => 'Kab. Muna Barat',
      'Kab. Wakatobi' => 'Kab. Wakatobi',
      'Kota Bau-Bau' => 'Kota Bau-Bau',
      'Kota Kendari' => 'Kota Kendari',

      // === GORONTALO ===
      'Kab. Boalemo' => 'Kab. Boalemo',
      'Kab. Bone Bolango' => 'Kab. Bone Bolango',
      'Kab. Gorontalo' => 'Kab. Gorontalo',
      'Kab. Gorontalo Utara' => 'Kab. Gorontalo Utara',
      'Kab. Pohuwato' => 'Kab. Pohuwato',
      'Kota Gorontalo' => 'Kota Gorontalo',

      // === SULAWESI BARAT ===
      'Kab. Majene' => 'Kab. Majene',
      'Kab. Mamasa' => 'Kab. Mamasa',
      'Kab. Mamuju' => 'Kab. Mamuju',
      'Kab. Mamuju Tengah' => 'Kab. Mamuju Tengah',
      'Kab. Pasangkayu' => 'Kab. Pasangkayu',
      'Kab. Polewali Mandar' => 'Kab. Polewali Mandar',

      // === MALUKU ===
      'Kab. Buru' => 'Kab. Buru',
      'Kab. Buru Selatan' => 'Kab. Buru Selatan',
      'Kab. Kepulauan Aru' => 'Kab. Kepulauan Aru',
      'Kab. Kepulauan Tanimbar' => 'Kab. Kepulauan Tanimbar',
      'Kab. Maluku Barat Daya' => 'Kab. Maluku Barat Daya',
      'Kab. Maluku Tengah' => 'Kab. Maluku Tengah',
      'Kab. Maluku Tenggara' => 'Kab. Maluku Tenggara',
      'Kab. Seram Bagian Barat' => 'Kab. Seram Bagian Barat',
      'Kab. Seram Bagian Timur' => 'Kab. Seram Bagian Timur',
      'Kota Ambon' => 'Kota Ambon',
      'Kota Tual' => 'Kota Tual',

      // === MALUKU UTARA ===
      'Kab. Halmahera Barat' => 'Kab. Halmahera Barat',
      'Kab. Halmahera Selatan' => 'Kab. Halmahera Selatan',
      'Kab. Halmahera Tengah' => 'Kab. Halmahera Tengah',
      'Kab. Halmahera Timur' => 'Kab. Halmahera Timur',
      'Kab. Halmahera Utara' => 'Kab. Halmahera Utara',
      'Kab. Kepulauan Sula' => 'Kab. Kepulauan Sula',
      'Kab. Pulau Morotai' => 'Kab. Pulau Morotai',
      'Kab. Pulau Taliabu' => 'Kab. Pulau Taliabu',
      'Kota Ternate' => 'Kota Ternate',
      'Kota Tidore Kepulauan' => 'Kota Tidore Kepulauan',

      // === PAPUA ===
      'Kab. Biak Numfor' => 'Kab. Biak Numfor',
      'Kab. Deiyai' => 'Kab. Deiyai',
      'Kab. Dogiyai' => 'Kab. Dogiyai',
      'Kab. Intan Jaya' => 'Kab. Intan Jaya',
      'Kab. Jayapura' => 'Kab. Jayapura',
      'Kab. Jayawijaya' => 'Kab. Jayawijaya',
      'Kab. Keerom' => 'Kab. Keerom',
      'Kab. Kepulauan Yapen' => 'Kab. Kepulauan Yapen',
      'Kab. Lanny Jaya' => 'Kab. Lanny Jaya',
      'Kab. Mamberamo Raya' => 'Kab. Mamberamo Raya',
      'Kab. Mamberamo Tengah' => 'Kab. Mamberamo Tengah',
      'Kab. Nabire' => 'Kab. Nabire',
      'Kab. Nduga' => 'Kab. Nduga',
      'Kab. Paniai' => 'Kab. Paniai',
      'Kab. Pegunungan Bintang' => 'Kab. Pegunungan Bintang',
      'Kab. Puncak' => 'Kab. Puncak',
      'Kab. Puncak Jaya' => 'Kab. Puncak Jaya',
      'Kab. Sarmi' => 'Kab. Sarmi',
      'Kab. Supiori' => 'Kab. Supiori',
      'Kab. Tolikara' => 'Kab. Tolikara',
      'Kab. Waropen' => 'Kab. Waropen',
      'Kab. Yahukimo' => 'Kab. Yahukimo',
      'Kab. Yalimo' => 'Kab. Yalimo',
      'Kota Jayapura' => 'Kota Jayapura',

      // === PAPUA BARAT ===
      'Kab. Fakfak' => 'Kab. Fakfak',
      'Kab. Kaimana' => 'Kab. Kaimana',
      'Kab. Manokwari' => 'Kab. Manokwari',
      'Kab. Manokwari Selatan' => 'Kab. Manokwari Selatan',
      'Kab. Maybrat' => 'Kab. Maybrat',
      'Kab. Pegunungan Arfak' => 'Kab. Pegunungan Arfak',
      'Kab. Raja Ampat' => 'Kab. Raja Ampat',
      'Kab. Sorong' => 'Kab. Sorong',
      'Kab. Sorong Selatan' => 'Kab. Sorong Selatan',
      'Kab. Tambrauw' => 'Kab. Tambrauw',
      'Kab. Teluk Bintuni' => 'Kab. Teluk Bintuni',
      'Kab. Teluk Wondama' => 'Kab. Teluk Wondama',
      'Kota Sorong' => 'Kota Sorong',

      // === PAPUA SELATAN ===
      'Kab. Asmat' => 'Kab. Asmat',
      'Kab. Boven Digoel' => 'Kab. Boven Digoel',
      'Kab. Mappi' => 'Kab. Mappi',
      'Kab. Merauke' => 'Kab. Merauke',
      'Kab. Mimika' => 'Kab. Mimika',
    ];
  }
}
